image: ubuntu:20.04

stages:
  - deploy_prod

before_script:
  - apt-get update -y
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$RUNNER_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

deploy_prod:
  stage: deploy_prod
  environment:
    name: production
    url: web.pressone.africa
  script:
    - ssh root@$DEPLOYMENT_SERVER_ADDRESS "
      mkdir -p /var/www/html
      && sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https
      && curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --yes --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
      && curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
      && sudo apt update
      && sudo apt install caddy
      && curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
      && export NVM_DIR="$HOME/.nvm"
      && source ~/.nvm/nvm.sh
      && nvm install 18.12.1
      && cd /var/www/
      && (git clone \"https://gitlab-ci-token:$GITLAB_CI_USER@gitlab.com/pressone-software/pressone-crm.git\" html || true)
      && cd html
      && export NODE_OPTIONS="--max_old_space_size=4096"
      && git fetch
      && git checkout master
      && git pull origin master
      && npm install
      && npm run build
      && (caddy start || true)
      && caddy reload
      && exit
      "
  tags:
    - pressone-shared
  only:
    - master
